# Generated by Django 5.2.4 on 2025-07-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(help_text='Enter url Facebook', verbose_name='Файсбук')),
                ('twitter', models.URLField(help_text='Enter url Twitter', verbose_name='Твитер')),
                ('linkedin', models.URLField(help_text='Enter url Linkedin', verbose_name='Линкедин')),
                ('instagram', models.URLField(help_text='Enter url Instagram', verbose_name='Instagram')),
                ('address', models.CharField(help_text='Нпишите свой адрес', max_length=155, verbose_name='Адрес')),
                ('email', models.EmailField(help_text='Enter your Email', max_length=254, verbose_name='Email')),
                ('working', models.CharField(help_text='Напшите время работы', max_length=155, verbose_name='Время работы')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
