# Generated by Django 5.2.4 on 2025-07-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsIndexPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome', models.CharField(max_length=155, verbose_name='Приветствие')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('image', models.ImageField(upload_to='settings', verbose_name='Фото')),
                ('title_about', models.CharField(max_length=155, verbose_name='Заголовка О нас')),
                ('description_about', models.TextField(verbose_name='Описание О нас')),
                ('end_description_about', models.CharField(max_length=155, verbose_name='Конец описание о нас')),
                ('title_viza', models.CharField(max_length=155, verbose_name='Заголовка Визы')),
                ('advantage', models.CharField(max_length=155, verbose_name='Примущество')),
                ('advantage_description', models.TextField(verbose_name='Описание примущество')),
                ('country_title', models.CharField(max_length=155, verbose_name='Страна заголовка')),
                ('faq', models.CharField(max_length=155, verbose_name='Часто задаваемые вопросы')),
                ('image_faq', models.ImageField(upload_to='settings', verbose_name='Фото FAQ')),
                ('faq2', models.CharField(max_length=155, verbose_name='Заголовка элитные программы ')),
                ('news_title', models.CharField(max_length=155, verbose_name='Заголовка Новости')),
            ],
            options={
                'verbose_name': 'Настройка Главной Страницы',
                'verbose_name_plural': 'Настройки Главной Страницы',
            },
        ),
    ]
