# Generated by Django 5.2.4 on 2025-07-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_settingsindexpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Банер',
            },
        ),
    ]
