# Generated by Django 5.2.4 on 2025-07-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsindexpage',
            name='imageabout1',
            field=models.ImageField(default=1, upload_to='settings', verbose_name='Фото о нас'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settingsindexpage',
            name='imageabout2',
            field=models.ImageField(default=1, upload_to='settings', verbose_name='Фото о нас'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settingsindexpage',
            name='imageabout3',
            field=models.ImageField(default=1, upload_to='settings', verbose_name='Фото о нас'),
            preserve_default=False,
        ),
    ]
