# Generated by Django 5.2.4 on 2025-07-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_settingsindexpage_imageabout1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('imageabout1', models.ImageField(upload_to='visa', verbose_name='Фото о нас')),
                ('imageabout2', models.ImageField(upload_to='visa', verbose_name='Фото о нас')),
                ('imageabout3', models.ImageField(upload_to='visa', verbose_name='Фото о нас')),
                ('imageabout4', models.ImageField(upload_to='visa', verbose_name='Фото о нас')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Виза',
            },
        ),
    ]
