# Generated by Django 5.2.4 on 2025-07-26 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_visa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visa',
            old_name='imageabout1',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='visa',
            old_name='imageabout2',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='visa',
            old_name='imageabout3',
            new_name='image3',
        ),
        migrations.RenameField(
            model_name='visa',
            old_name='imageabout4',
            new_name='image4',
        ),
    ]
